//
//  CategoryColors.swift
//  tiz
//
//  Created by tiziano on 5/17/19.
//  Copyright © 2019 tz. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class CategoryColors : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawCanvas1(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 160, height: 91), resizing: ResizingBehavior = .aspectFit, blueCategory: CGFloat = 0, greenCategory: CGFloat = 0, orangeCategory: CGFloat = 0, yellowCategory: CGFloat = 0) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 160, height: 91), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 160, y: resizedFrame.height / 91)


        //// Color Declarations
        let orange_light = UIColor(red: 0.988, green: 0.498, blue: 0.384, alpha: 1.000)
        let blue = UIColor(red: 0.196, green: 0.251, blue: 0.361, alpha: 1.000)
        let yellow = UIColor(red: 1.000, green: 0.984, blue: 0.595, alpha: 1.000)
        let green = UIColor(red: 0.000, green: 0.678, blue: 0.710, alpha: 1.000)
        let lightOrange = UIColor(red: 0.973, green: 0.710, blue: 0.000, alpha: 1.000)
        let blue2_light = UIColor(red: 0.196, green: 0.251, blue: 0.361, alpha: 0.400)
        let orange_light_light = UIColor(red: 0.988, green: 0.498, blue: 0.384, alpha: 0.400)
        let yellow2_light = UIColor(red: 0.988, green: 0.984, blue: 0.890, alpha: 0.400)
        let green_light = UIColor(red: 0.000, green: 0.678, blue: 0.710, alpha: 0.400)

        //// Variable Declarations
        let blueCategoryIncrement: CGFloat = 145 * blueCategory
        let greenCategoryIncrement: CGFloat = 145 * greenCategory
        let orangeCategoryIncrement4: CGFloat = 145 * orangeCategory
        let yellowCategoryIncrement3: CGFloat = 145 * yellowCategory

        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: 2.5, y: 1.5, width: 9, height: 88))
        lightOrange.setStroke()
        rectanglePath.lineWidth = 1
        context.saveGState()
        context.setLineDash(phase: 0, lengths: [1, 1])
        rectanglePath.stroke()
        context.restoreGState()


        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRect(x: 8, y: 8, width: 146, height: 13))
        blue2_light.setFill()
        rectangle2Path.fill()


        //// Rectangle 3 Drawing
        let rectangle3Path = UIBezierPath(rect: CGRect(x: 8, y: 26, width: 146, height: 13))
        green_light.setFill()
        rectangle3Path.fill()


        //// Rectangle 4 Drawing
        let rectangle4Path = UIBezierPath(rect: CGRect(x: 8, y: 46, width: 146, height: 13))
        yellow2_light.setFill()
        rectangle4Path.fill()


        //// Rectangle 5 Drawing
        let rectangle5Path = UIBezierPath(rect: CGRect(x: 8, y: 68, width: 146, height: 13))
        orange_light_light.setFill()
        rectangle5Path.fill()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 8.5, y: 14.5))
        bezierPath.addLine(to: CGPoint(x: 153.5, y: 14.5))
        blue.setStroke()
        bezierPath.lineWidth = 13
        context.saveGState()
        context.setLineDash(phase: 0, lengths: [blueCategoryIncrement, 145])
        bezierPath.stroke()
        context.restoreGState()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        UIColor.black.setStroke()
        bezier2Path.lineWidth = 1
        bezier2Path.stroke()


        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.move(to: CGPoint(x: 8.5, y: 32.5))
        bezier3Path.addLine(to: CGPoint(x: 153.5, y: 32.5))
        green.setStroke()
        bezier3Path.lineWidth = 13
        context.saveGState()
        context.setLineDash(phase: 0, lengths: [greenCategoryIncrement, 145])
        bezier3Path.stroke()
        context.restoreGState()


        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.move(to: CGPoint(x: 9.5, y: 52.5))
        bezier4Path.addLine(to: CGPoint(x: 154.5, y: 52.5))
        yellow.setStroke()
        bezier4Path.lineWidth = 13
        context.saveGState()
        context.setLineDash(phase: 0, lengths: [yellowCategoryIncrement3, 145])
        bezier4Path.stroke()
        context.restoreGState()


        //// Bezier 5 Drawing
        let bezier5Path = UIBezierPath()
        bezier5Path.move(to: CGPoint(x: 8.5, y: 74.5))
        bezier5Path.addLine(to: CGPoint(x: 153.5, y: 74.5))
        orange_light.setStroke()
        bezier5Path.lineWidth = 13
        context.saveGState()
        context.setLineDash(phase: 0, lengths: [orangeCategoryIncrement4, 145])
        bezier5Path.stroke()
        context.restoreGState()
        
        context.restoreGState()

    }




    @objc(CategoryColorsResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
