//
//  Trackertask.swift
//  cw2
//
//  Created by tiziano on 5/17/19.
//  Copyright © 2019 tz. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class Trackertask : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawCanvas1(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 160, height: 155), resizing: ResizingBehavior = .aspectFit, failure: CGFloat = 0, achive: CGFloat = 0) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 160, height: 155), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 160, y: resizedFrame.height / 155)


        //// Color Declarations
        let colorFail = UIColor(red: 0.963, green: 0.004, blue: 0.004, alpha: 1.000)
        let colorFail2 = UIColor(red: 0.574, green: 0.000, blue: 0.000, alpha: 1.000)
        let greenPower = UIColor(red: 0.151, green: 0.823, blue: 0.565, alpha: 1.000)
        let white = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let failRed = UIColor(red: 0.619, green: 0.000, blue: 0.000, alpha: 1.000)

        //// Gradient Declarations
        let gradientFail = CGGradient(colorsSpace: nil, colors: [colorFail.cgColor, colorFail2.cgColor] as CFArray, locations: [0, 1])!
        let gradientOK = CGGradient(colorsSpace: nil, colors: [UIColor.green.cgColor, UIColor.green.blended(withFraction: 0.5, of: greenPower).cgColor, greenPower.cgColor] as CFArray, locations: [0, 0, 1])!

        //// Variable Declarations
        let expr_failure: CGFloat = 302 * failure
        let sad = failure < 0.98 ? white : failRed
        let expr_achive: CGFloat = 220 * achive
        let one = achive < 0.22 ? white : greenPower
        let two = achive < 0.45 ? white : greenPower
        let three = achive < 0.7 ? white : greenPower
        let four = achive < 0.98 ? white : greenPower

        //// Oval Drawing
        context.saveGState()
        context.setAlpha(0.2)
        context.beginTransparencyLayer(auxiliaryInfo: nil)

        let ovalPath = UIBezierPath(ovalIn: CGRect(x: 25, y: 21, width: 111, height: 111))
        context.saveGState()
        ovalPath.addClip()
        context.drawLinearGradient(gradientFail, start: CGPoint(x: 80.5, y: 21), end: CGPoint(x: 80.5, y: 132), options: [])
        context.restoreGState()
        UIColor.black.setStroke()
        ovalPath.lineWidth = 2
        ovalPath.stroke()

        context.endTransparencyLayer()
        context.restoreGState()


        //// Oval 2 Drawing
        let oval2Path = UIBezierPath(ovalIn: CGRect(x: 38, y: 34, width: 85, height: 85))
        UIColor.white.setFill()
        oval2Path.fill()
        UIColor.black.setStroke()
        oval2Path.lineWidth = 2
        oval2Path.stroke()


        //// Oval 6 Drawing
        context.saveGState()
        context.setAlpha(0.2)
        context.beginTransparencyLayer(auxiliaryInfo: nil)

        let oval6Path = UIBezierPath(ovalIn: CGRect(x: 38, y: 34, width: 85, height: 85))
        context.saveGState()
        oval6Path.addClip()
        context.drawLinearGradient(gradientOK, start: CGPoint(x: 80.5, y: 34), end: CGPoint(x: 80.5, y: 119), options: [])
        context.restoreGState()
        UIColor.black.setStroke()
        oval6Path.lineWidth = 2
        oval6Path.stroke()

        context.endTransparencyLayer()
        context.restoreGState()


        //// Oval 3 Drawing
        let oval3Path = UIBezierPath(ovalIn: CGRect(x: 52, y: 48, width: 57, height: 57))
        UIColor.white.setFill()
        oval3Path.fill()
        UIColor.black.setStroke()
        oval3Path.lineWidth = 2
        oval3Path.stroke()


        //// Oval 4 Drawing
        let oval4Path = UIBezierPath(ovalIn: CGRect(x: 32, y: 28, width: 97, height: 97))
        colorFail2.setStroke()
        oval4Path.lineWidth = 10
        context.saveGState()
        context.setLineDash(phase: 0, lengths: [expr_failure, 301])
        oval4Path.stroke()
        context.restoreGState()


        //// Oval 5 Drawing
        let oval5Path = UIBezierPath(ovalIn: CGRect(x: 45.5, y: 41, width: 70.5, height: 71))
        greenPower.setStroke()
        oval5Path.lineWidth = 10
        context.saveGState()
        context.setLineDash(phase: 0, lengths: [expr_achive, 301])
        oval5Path.stroke()
        context.restoreGState()


        //// Star 2 Drawing
        let star2Path = UIBezierPath()
        star2Path.move(to: CGPoint(x: 79.5, y: 134.5))
        star2Path.addLine(to: CGPoint(x: 81.97, y: 138.1))
        star2Path.addLine(to: CGPoint(x: 86.16, y: 139.34))
        star2Path.addLine(to: CGPoint(x: 83.49, y: 142.8))
        star2Path.addLine(to: CGPoint(x: 83.61, y: 147.16))
        star2Path.addLine(to: CGPoint(x: 79.5, y: 145.7))
        star2Path.addLine(to: CGPoint(x: 75.39, y: 147.16))
        star2Path.addLine(to: CGPoint(x: 75.51, y: 142.8))
        star2Path.addLine(to: CGPoint(x: 72.84, y: 139.34))
        star2Path.addLine(to: CGPoint(x: 77.03, y: 138.1))
        star2Path.close()
        one.setFill()
        star2Path.fill()
        UIColor.black.setStroke()
        star2Path.lineWidth = 1
        star2Path.stroke()


        //// Star 3 Drawing
        let star3Path = UIBezierPath()
        star3Path.move(to: CGPoint(x: 15.5, y: 68.5))
        star3Path.addLine(to: CGPoint(x: 17.97, y: 72.1))
        star3Path.addLine(to: CGPoint(x: 22.16, y: 73.34))
        star3Path.addLine(to: CGPoint(x: 19.49, y: 76.8))
        star3Path.addLine(to: CGPoint(x: 19.61, y: 81.16))
        star3Path.addLine(to: CGPoint(x: 15.5, y: 79.7))
        star3Path.addLine(to: CGPoint(x: 11.39, y: 81.16))
        star3Path.addLine(to: CGPoint(x: 11.51, y: 76.8))
        star3Path.addLine(to: CGPoint(x: 8.84, y: 73.34))
        star3Path.addLine(to: CGPoint(x: 13.03, y: 72.1))
        star3Path.close()
        two.setFill()
        star3Path.fill()
        UIColor.black.setStroke()
        star3Path.lineWidth = 1
        star3Path.stroke()


        //// Star 4 Drawing
        let star4Path = UIBezierPath()
        star4Path.move(to: CGPoint(x: 80.5, y: 5.5))
        star4Path.addLine(to: CGPoint(x: 82.97, y: 9.1))
        star4Path.addLine(to: CGPoint(x: 87.16, y: 10.34))
        star4Path.addLine(to: CGPoint(x: 84.49, y: 13.8))
        star4Path.addLine(to: CGPoint(x: 84.61, y: 18.16))
        star4Path.addLine(to: CGPoint(x: 80.5, y: 16.7))
        star4Path.addLine(to: CGPoint(x: 76.39, y: 18.16))
        star4Path.addLine(to: CGPoint(x: 76.51, y: 13.8))
        star4Path.addLine(to: CGPoint(x: 73.84, y: 10.34))
        star4Path.addLine(to: CGPoint(x: 78.03, y: 9.1))
        star4Path.close()
        three.setFill()
        star4Path.fill()
        UIColor.black.setStroke()
        star4Path.lineWidth = 1
        star4Path.stroke()


        //// Star 5 Drawing
        let star5Path = UIBezierPath()
        star5Path.move(to: CGPoint(x: 147.5, y: 68.5))
        star5Path.addLine(to: CGPoint(x: 149.97, y: 72.1))
        star5Path.addLine(to: CGPoint(x: 154.16, y: 73.34))
        star5Path.addLine(to: CGPoint(x: 151.49, y: 76.8))
        star5Path.addLine(to: CGPoint(x: 151.61, y: 81.16))
        star5Path.addLine(to: CGPoint(x: 147.5, y: 79.7))
        star5Path.addLine(to: CGPoint(x: 143.39, y: 81.16))
        star5Path.addLine(to: CGPoint(x: 143.51, y: 76.8))
        star5Path.addLine(to: CGPoint(x: 140.84, y: 73.34))
        star5Path.addLine(to: CGPoint(x: 145.03, y: 72.1))
        star5Path.close()
        four.setFill()
        star5Path.fill()
        UIColor.black.setStroke()
        star5Path.lineWidth = 1
        star5Path.stroke()


        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        four.setFill()
        bezierPath.fill()
        UIColor.black.setStroke()
        bezierPath.lineWidth = 1
        bezierPath.stroke()


        //// Group
        //// Oval 7 Drawing
        let oval7Path = UIBezierPath(ovalIn: CGRect(x: 63.5, y: 63.5, width: 5, height: 5))
        four.setFill()
        oval7Path.fill()
        sad.setStroke()
        oval7Path.lineWidth = 1
        oval7Path.stroke()


        //// Oval 8 Drawing
        let oval8Path = UIBezierPath(ovalIn: CGRect(x: 90.5, y: 63.5, width: 5, height: 5))
        four.setFill()
        oval8Path.fill()
        sad.setStroke()
        oval8Path.lineWidth = 1
        oval8Path.stroke()


        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 67.5, y: 92.5))
        bezier2Path.addLine(to: CGPoint(x: 71.5, y: 88.5))
        bezier2Path.addLine(to: CGPoint(x: 89.5, y: 88.5))
        bezier2Path.addLine(to: CGPoint(x: 92.5, y: 92.5))
        sad.setFill()
        bezier2Path.fill()
        sad.setStroke()
        bezier2Path.lineWidth = 1
        bezier2Path.stroke()
        
        context.restoreGState()

    }




    @objc(TrackertaskResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.

        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }

            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)

            switch self {
                case .aspectFit:
                    scales.width = min(scales.width, scales.height)
                    scales.height = scales.width
                case .aspectFill:
                    scales.width = max(scales.width, scales.height)
                    scales.height = scales.width
                case .stretch:
                    break
                case .center:
                    scales.width = 1
                    scales.height = 1
            }

            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}



private extension UIColor {
    func blended(withFraction fraction: CGFloat, of color: UIColor) -> UIColor {
        var r1: CGFloat = 1, g1: CGFloat = 1, b1: CGFloat = 1, a1: CGFloat = 1
        var r2: CGFloat = 1, g2: CGFloat = 1, b2: CGFloat = 1, a2: CGFloat = 1

        self.getRed(&r1, green: &g1, blue: &b1, alpha: &a1)
        color.getRed(&r2, green: &g2, blue: &b2, alpha: &a2)

        return UIColor(red: r1 * (1 - fraction) + r2 * fraction,
            green: g1 * (1 - fraction) + g2 * fraction,
            blue: b1 * (1 - fraction) + b2 * fraction,
            alpha: a1 * (1 - fraction) + a2 * fraction);
    }
}
